### ISSUE TITLE
jsroot and JupyterLab

### ISSUE THREAD

**Issue by wgseligman** [root-project/jsroot#166] opened 2018-08-09 22:35 UTC
I have no problems using jsroot in jupyter. I have no problems making plots in general in jupyter or jupyterlab. But when I use jsroot in python within JupyterLab; e.g.
```
import ROOT
%jsroot on
canvas = ROOT.TCanvas()
test = ROOT.TH1D("example","example",100,-5.,5.)
test.FillRandom("gaus",100000)
test.Draw()
canvas.Draw()
```
or in the ROOT C++ kernel, e.g.,
```
%jsroot on
TCanvas my_canvas("canvas","canvas title",800,600);
TH1D example("example","example histogram",100,-3,3);
example.FillRandom("gaus",10000);
example.Draw();
my_canvas.Draw();
```
I just see a blank area in the output that's the same size of the plot I expect. If I turn `%jsroot off` in both the above examples, the plot is produced. If I use the same notebooks in "plain old jupyter", the plots appear with `%jsroot on`. 

I've tried this on two different machines/OSes with the same results: 
OS - CentOS 7
Python version - 3.6.5
ROOT version - 6.14.02

OS - Mac OS 10.11.6
Python version - 3.6.6
ROOT version - 6.14.00

Any ideas?

**Comment by linev** [comment] 2018-08-10 07:19
Can you check message in browser console?
And probably @etejedor can help you more.

**Comment by etejedor** [comment] 2018-08-10 07:39
The JSROOT graphics have not yet been integrated with JupyterLab (which is still in beta version until beginning of next year). It is also in the plans of the SWAN notebook service at CERN to work on the integration with JupyterLab, but this effort has not started yet.
Any contribution is of course welcome - it would be a matter of checking what has changed in the IPython / Jupyter API for what concerns the rendering of JavaScript graphics.

**Comment by wgseligman** [comment] 2018-08-10 09:56
At least I now know that this isn't an error on my part. Thanks!

**Comment by DraTeots** [comment] 2019-05-15 01:23
First, to make it work in jupyterlab, there is a workaround. Add the next code in a cell before:

```
%%javascript
if (!requirejs) {
    var s = document.createElement('script');
    s.src='https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js';
    document.body.appendChild(s);
}
```
It solves the problem.

**Comment by linev** [comment] 2019-05-15 07:10
> It solves the problem.

But require.js alone does not help. 

JSROOT with Jupyter Notebooks was reusing different modules (d3, jquery, jquery-ui) which were registered to require.js in advance. If none of such modules provided with jupyterlab, there should be no any advantage of loading or not loading require.js.

Probably, there is simple fix in the code around creation of JSROOT graphics to avoid require statement at all. I guess, it is here:

https://github.com/root-project/root/blob/master/bindings/pyroot/JupyROOT/helpers/utils.py#L51-L63

One can avoid use of require syntax there completely.

**Comment by DraTeots** [comment] 2019-05-16 02:19
Yes! I And we (users) are patiently waiting when it will be changed there. And the right jupyterlab extension is developed (which is the proposed way to go for jupyterlab now) too. 

Btw I tried to write the extension but get stumbled a bit on what exactly is exported from jsroot modules

**Comment by etejedor** [comment] 2019-05-16 07:33
Just to add another piece of information to this conversation, in July we will have a summer student in the ROOT team that will work on the integration of ROOT JS graphics and GUI in JupyterLab.

**Comment by DraTeots** [comment] 2019-05-16 17:50
Great news! 

Actually, I'm from Electron Ion Collider software consortium (particularly from Jefferson Lab) . We are going to try to use JupyterLab as an entry point for new (and not only) users for our simulation and reconstruction software. The idea, is to provide the simulation environment (with ROOT, Geant, our packets) with jupyterlab as UI on top of it. 

So we started to write some jupyterlab extensions like x-root mime renderers. This could be a good collaboration point, when the student will arrive.

**Comment by etejedor** [comment] 2019-05-17 08:04
Hi Dimtry, in the ROOT team we are in close contact with EIC colleagues, in particular with Markus Diefenthaler. In fact, one of our team members, Lorenzo Moneta, is attend the EIC Software Meeting next week and will give a talk about ROOT.

I also wanted to point out that at CERN we have the SWAN service (https://swan.cern.ch), which provides a Jupyter notebook interface on top of CVMFS (software) and EOS (data). This is a presentation of the service at the Jupytercon:
https://conferences.oreilly.com/jupyter/jup-ny/public/schedule/detail/68359
We are planning to migrate the classic Jupyter interface to Jupyterlab.

There is also a version of SWAN that is installable on premises, called ScienceBox:
https://sciencebox.web.cern.ch/sciencebox/

**Comment by diocas** [comment] 2019-05-17 08:29
Let me just add that the SWAN/CERNBox versions you see in ScienceBox are old compared to what we have in production at CERN. But, if you switch to the uboxed/kuboxed branch called "update_sciencebox", you will get the latest stuff. This will be merged in the near future, but for now it's still missing some documentation to be ready. If you are interested in trying and have any doubt, please let us know.

**Comment by linev** [comment] 2019-05-17 08:32
I reopen this issue - seems to be there is interest to have it running.
There is also related Jira issue
https://sft.its.cern.ch/jira/browse/ROOT-10116

**Comment by wgseligman** [comment] 2019-05-17 09:58
> First, to make it work in jupyterlab, there is a workaround. Add the next code in a cell before:
> 
> ```
> %%javascript
> if (!requirejs) {
>     var s = document.createElement('script');
>     s.src='https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js';
>     document.body.appendChild(s);
> }
> ```
> 
> It solves the problem.

Thanks DraTeots, but I'm afraid this did not solve the problem for me. I get the error that 'requirejs' is undefined. I fiddled with installing the require.js package with npm, but that didn't change anything. 

Based on the other comments I see in this thread, I think the underlying issue is that I don't understand how javascript+jupyterlab work together. Iinstructions like yours assume that I'll know what to do if some js component is missing. Clearly I don't! 

As a side note, the work I'm doing is part of a jupyterhub installation that's used by a couple of dozen people. So any solution with jsroot in jupyterlab has to work transparently for all the users. If they have to execute special cells to make jsroot work, then they simply won't use jsroot, jupyterlab, or both.

**Comment by DraTeots** [comment] 2019-05-17 17:45
@etejedor The world is small! We are on the same team with Markus, our offices are next to each other. During the very same conference, the next week on Tuesday I will have a presentation of our prototype.

@wgseligman Yes, unfortunately loading modules in Javascript became convoluted. Historically there where no "import" command in javascript so many solutions where developed to solve it. Each solution has PROC and CONS and it is the part, that has been changed in jupyterlab. Moreover, as the result, large projects have pretty nontransparent build systems in JS, which require even more learning than, say, cmake for C++. 


When you install something with npm, in general it "stays" on server side. It then should get its way to your browser one way or another. The best solution would be just fixing it on ROOT side, I guess.

**Comment by DraTeots** [comment] 2019-06-13 07:10
Hi All! 

On that EIC software meeting I actually showed a jupyter lab extension, that can render root files and geometry inside jupyter lab. Initially the extension used iframe, which is simple, but has too many limitations. Rewriting this to directly use jsroot API got me to stack with something similar to #165 

The thing I don't really like in the solution of #165 is that it looks more like workaround. The <script> is injected to the DOM, we wait it to be loaded and then use window.ROOT. 

From the user's perspective, I would prefer just to use jsroot as the standard javascript library which exports something, that I just import and use. 

It is essentially important in terms of this ticket for 3 reasons:

1. Jupyterlab is moving in direction of restricting of using uncontrolled javascript. Such side jafascript modules should be embedded as extensions. The extensions are compiled as jupyterlab modules. Taking JSROOT and the way it is used in #165 final demo, it is a bit harder to set the things up and debug under jupyterlab from one side and it is really not going along with how one suppose to write extensions on the other.  

2. MIME renderer  (which is the Jupyterlab abstraction for rendering different types of files) create a new instance for each opened file. Since loading <script> with jsroot takes some time, one have to control which renderer spawning this first, accessing the global Jupyterlab context, etc. Nothing that can't be solved but it start looking even more like workaround over workarounds. 

3. The most parts (and extension interfaces too) of Jupyterlab is written in Typescript. It is streamlined there and is easy to use. Writing JSRoot definitions for the Typescript seems even more cumbersome. 

So could you add/change jsroot api so that it could be used as a "standard" JS library?

P.S. I understand the reason about dynamic module loading. And don't mind an extra initialization step or a lot of includes.

**Comment by linev** [comment] 2019-06-13 14:01
> So could you add/change jsroot api so that it could be used as a "standard" JS library?
@DraTeots 
That do you mean - "standard JS library"?

JSROOT supports require.js and node.js modules.
The fact is, that when you call ``require("jsroot")``, only basic JSROOT functionality is loaded.
And only when real object rendering should be performed, appropriate sub-modules of JSROOT are loaded. 

Do you need something like  ``require("jsroot-all")``?
Or may be you need to support other kind of loader?

**Comment by DraTeots** [comment] 2019-06-13 20:54
By "standard" I mean ES6 import and export semantics. 
https://webpack.js.org/api/module-methods/

But the problems come from WebPack modules import. It actually supports require syntax too, but whatever I tried to do, gets me errors like this:
`ModuleNotFoundError: Module not found: Error: Can't resolve 'JSRootCore' in '/home/romanov/venv/share/jupyter/lab/staging/node_modules/jsroot/scripts'
`
(The path is definitely there)

With a lot of experiments trying to import stuff (even putting JSroot next to my source code),  made me think that the problem in what and how is get exported out of the module.

**Comment by linev** [comment] 2019-06-17 19:00
> It actually supports require syntax too, but whatever I tried to do, building the extension (which happens on jupyterlab side) gives me errors like 

May be this is source of the problem.
There is special block in JSRoot for require.js config; may be similar should be provided for WebPack.

On the long run I plan to "modernize" JSROOT code loading, but not yet sure which approach to choose.

I will try to check WebPack problem once I am back from the vacations in begin of July.

**Comment by DraTeots** [comment] 2019-07-08 08:43
Found this npm package

https://www.npmjs.com/package/jupyterlab_rootjs/v/0.1.2

But...
1. What it does - it imports require.js (as we discussed above)
2. It doesn't work as jupyterlab reached 1.0.1 and something changed. 

How is the vacation? Any updates on webpack?

**Comment by linev** [comment] 2019-07-08 09:14
Hi,

> Found this npm package
> https://www.npmjs.com/package/jupyterlab_rootjs/v/0.1.2

I was not aware about this package - we should ask developer @jdbrice about project state.

As I know, there is summer student in CERN working on this topic. 
And seems to be now JSROOT already running in JupyterLab. 
But Enric (@etejedor) or Bertrand (@bellenot) can comment more.

**Comment by philipleindecker** [comment] 2019-07-08 13:21
Hi, 

I think I found a solution to display the interactive graphics while jsroot on. 

At first I added the following line right before the requirejs [script](https://github.com/root-project/root/blob/master/bindings/pyroot/JupyROOT/helpers/utils.py#L51-L63) so that requirejs is imported correctly.

`<script src="/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f" type="text/javascript" charset="utf-8"></script>`

This line already solves many issues, but some interactive graphics still won’t work. [Example](https://nbviewer.jupyter.org/github/dpiparo/swanExamples/blob/master/notebooks/Geometry_Visualisation_cpp/Geometry_Visualisation_cpp.ipynb)
Therefore I embedded the HTML code, which is generated in the _getJsDiv function, in an iFrame, which then displays the graphic properly.
The new _getJsDiv function looks like this:

```
def _getJsDiv(self):
        html = HTML(self._getJsCode()).data
        with open('html_file.html', 'w') as f:
            f.write(html)
        return IFrame(src='html_file.html', width=_jsCanvasHeight, height=_jsCanvasHeight)
```

Do not forget to import iFrame with:

`from IPython.display import IFrame`

What do you think of this approach?

**Comment by linev** [comment] 2019-07-08 13:30
Hi,

> This line already solves many issues, but some interactive graphics still won’t work. 
> https://nbviewer.jupyter.org/github/dpiparo/swanExamples/blob/master/notebooks/Geometry_Visualisation_cpp/Geometry_Visualisation_cpp.ipynb

Your example works for me.

> Therefore I embedded the HTML code, which is generated in the _getJsDiv function, in an iFrame, which then displays the graphic properly.

And I am not sure that I fully understand the code. It dumps all HTML structures into file and then opens such file in iframe. I do not think it will work. That about WebGL? That about JavaScript code?

Even if iframe will work - it has to load complete JSROOT for every new drawing. Can be overkill.

**Comment by philipleindecker** [comment] 2019-07-08 14:00
@linev Do you mean my Example works for you in JupyterLab (not in the old Jupyter Notebook) without doing this:

> At first I added the following line right before the requirejs script so that requirejs is imported correctly.

**Comment by DraTeots** [comment] 2019-07-08 14:10
Em... No. 
If you read this topic closely, adding require.js is a known "solution" for some time now for jupyterlab. Even that library above (if you look the code) just does that. Adds requirejs. 

The problem is that it is VERY unstable. It works some times and then it starts bugging. Then you have to spend several minutes reloading the window and reloading cells with kernels. I believe this doesn't work when you have several tabs open in jupyter lab and called cells in some order. 

As usual, it never works for users and we have to put "jsroot off" for their convenience. 

I believe the reliable solution would be to add jsroot through jupyterlab extension. And to fulfill this one has to figure out why webpack is mad at JSRoot

**Comment by linev** [comment] 2019-07-08 14:12
@philipleindecker 

> Do you mean my Example works for you in JupyterLab

No, just opening your link I see geometry drawing.

**Comment by linev** [comment] 2019-07-08 14:33
> I believe the reliable solution would be to add jsroot through jupyterlab extension

But which loading method should be used in such `jupyterlab extension`?
According to `https://webpack.js.org/api/module-methods/` there are at least three different methods: 
* import/export
* CommonJS
* AMD

AMD more or less implemented in JSROOT. Probably, one should try it? Can one use `define` calls without loading require.js? Can I distinguish between webpack define and require.js define? 

CommonJS is used in Node.js, not sure if it works in browsers - while it loads scripts synchronously. 

`export/import` has some limitations - not supported fully dynamic paths. At this can be showstopper for JSROOT.

Main problem for me - I have no idea about JupyterLab and no any test environment.
I cannot spent several weeks to installing and understanding how it works and that are the problems.
I can adjust JSROOT code if somebody clarify that should be changed - but having in mind that there are many other use-cases for JSROOT beside JupyterLab. And they should work as before.

**Comment by jdbrice** [comment] 2019-07-10 13:37
Hi all,

Sorry I don't check this email too often. I developed the
jupyterlab_rootjs, but as has already been noted, there are probably better
ways to make this extension - and since I have not updated jupyterlab /
JSROOT in a while I would not be surprised if there have been breaking
changes (breaking to my extension). I would be interested in helping
continue development on this type of extension. Also if you guys would like
to use the name "jupyter_rootjs" we can discuss that.

Best,
Daniel

**Comment by DraTeots** [comment] 2019-07-10 18:31
Hi Daniel!
Thanks for your response! Indeed, jupyter_rootjs doesn't work with JupyterLab 1.0.1 (and 1.0.0 too). If you could help putting it back on rails - it would help us a lot!

**Comment by DraTeots** [comment] 2019-07-12 05:26
@jdbrice Created a [PR](https://github.com/jdbrice/jupyterlab_rootjs/pull/3)

**Comment by DraTeots** [comment] 2019-07-12 06:09
The only problem that it is not working) At all. It is some stuff created by copying pasting another extension with to mime renderers for ```application/vnd.rootjs_load.v0+json``` which serves only for another python project here

https://github.com/jdbrice/root-io/blob/5b8441198744f312e824ced7436a7d7aeeff9372/rootio/Histogram.py#L239

**Comment by jdbrice** [comment] 2019-07-12 13:16
Hi Dmitry,
What does this mean?

> The only problem that it is not working) At all. It is some stuff created
> by copying pasting another extension with to mime renderers for
> application/vnd.rootjs_load.v0+json which serves only for another python
> project here


It may not be very clear how my extension works to others, since I have
only used it with students at my institution. But I can make it work out of
the box for ROOTJS. The project you refer to was a pre-cursor of types to
the upROOT pure python project. The plan is to add a compatibility layer to
upROOT to make it work with this plugin also (for visual parts).

But I am open to suggestions.

Best,
Daniel

**Comment by philipleindecker** [comment] 2019-07-15 13:22
Hi,

I looked a little bit deeper into why the iFrame solution works which I posted last week and I think I found a different solution now without the iFrames.

> Therefore I embedded the HTML code, which is generated in the _getJsDiv function, in an iFrame, which then displays the graphic properly.

I found out that in Jupyter Lab the jsUID for the Divs which contain the interactive javascript can exist more than once in a Jupyer Lab Session. So the _getUID(self) function ([here](https://github.com/root-project/root/blob/master/bindings/pyroot/JupyROOT/helpers/utils.py#L373-L379)) only works for a single file but not when multiple tabs are open in Jupyter Lab. 

So as a quick fix I replaced this [line](https://github.com/root-project/root/blob/master/bindings/pyroot/JupyROOT/helpers/utils.py#L352) with the following: 

`jsUID = int((datetime.datetime.now()-datetime.datetime(1970,1,1)).total_seconds()*1000)`

So with this line every file has a different jsUID at the beginning which is then incremented again by the _getUID(self) function.

Again, this solution requires importing requirejs as I described earlier.

> At first I added the following line right before the requirejs script so that requirejs is imported correctly.

The reason why the iFrames also work seems to be the fact that each iFrame is considered as a completely separate element on the page. Therefore I does not matter wether they have the same jsUID or not and therefore the Divs do not interfere with each other.

What do you think of this solution?

**Comment by DraTeots** [comment] 2019-07-18 23:50
Hi!
To me seems very similar to what ipywidgets are doing. 
https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Low%20Level.html

**Comment by DraTeots** [comment] 2020-01-20 02:15
Hi!
Are there any updates on that issue? 

(I'm back to trying to resolve it but first wanted to check what are the plans about webpack, rehauling imports, etc.)

**Comment by linev** [comment] 2020-01-20 08:07
Hi,

Yes, there are news. 
Next ROOT release provides support of JSROOT in JupyterLab.
For more details please contact Enric @etejedor

**Comment by DraTeots** [comment] 2020-01-20 09:20
Excellent news! Thank you! 
With recent updates to EIC (CD-0 started) we have coming users and desperately need this. 

I saw branch 6-20, will try to contact Enric if it is ready to try.

**Comment by etejedor** [comment] 2020-01-20 09:41
I confirm the feature is ready to try!

**Comment by DraTeots** [comment] 2020-02-27 15:16
Looks like it is not working with standalone jupyterlab server:

```
The resource from “http://127.0.0.1:8888/static/scripts/JSRootCore.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
auto-K
Loading failed for the <script> with source “http://127.0.0.1:8888/static/scripts/JSRootCore.js”. auto-K:1:1
Error: Script error for "scripts/JSRootCore"
http://requirejs.org/docs/errors.html#scripterror require.js:168:17
    makeError http://127.0.0.1:8888/static/components/requirejs/require.js:168
    onScriptError http://127.0.0.1:8888/static/components/requirejs/require.js:1735
```

Please, let me know If it is something that you can't quickly guess, then I probably will try to recreate the case in the sandbox environment. 

P.S. I'm confused about (“text/html”) mismatch (X-Content-Type-Options: nosniff), usually it is a server or a linux mime DB issue, but It is just a fresh jupyterlab installation along with ROOT+PyROOT.

**Comment by linev** [comment] 2020-02-27 15:20
> I'm confused about (“text/html”) mismatch

Strange. It is responsibility of Jupyter web server to set correct MIME types - we do not have access to such configuration. Can you check that `http://127.0.0.1:8888/static/scripts/JSRootCore.js` file exists?

**Comment by DraTeots** [comment] 2020-02-29 02:17
Exactly! I also don't know who serves `“http://127.0.0.1:8888/static/scripts/JSRootCore.js”` and guessed that maybe root initialization scripts are tuning jupyterlab configuration for it? Or maybe it is not served and ("text/html") is actually 404 

Ok, I created a test sandbox with the problem. There is a bare ubuntu, root 6-20 (fresh install from today) + pip installed jupyterlab. 

With docker installed, please run

```bash
docker run --rm -it -p 8888:8888  --init eicdev/ejana-ubuntu18-prereq
```

It will run a jupyterlab on localhost:8888 with a single jupyter notebook that shows the issue

### What is on that docker:

It is bare ubuntu image, installed packages from root build prerequisites, root built with:

```
cmake -Wno-dev 
-DCMAKE_INSTALL_PREFIX=/container/app/root
-Dgdml=ON 
-Dminuit2=ON  
-DPYTHON_EXECUTABLE=/usr/bin/python3  
-Dmathmore=ON 
-Dbuiltin_gsl=ON
```

Along with it is jupyterlab installed and run:

```bash
RUN python3 -m pip install jupyterlab

CMD source /container/app/root/root-v6-20-00/bin/thisroot.sh &&\
    jupyter lab --ip=0.0.0.0 --no-browser \
    --NotebookApp.custom_display_url=http://127.0.0.1:8888 \
    --NotebookApp.token=''
```

The docker image code is located here:
https://gitlab.com/eic/containers/-/tree/master/docker%2Fdevops%2Fejana-ubuntu18-prereq

**Comment by linev** [comment] 2020-03-04 07:39
> Exactly! I also don't know who serves “http://127.0.0.1:8888/static/scripts/JSRootCore.js”

It should be web server, which is used in Jupyter. Appropriate configuration is provied in "jupyter_notebook_config.py" file when nbmain is started. 
If you have old configuration file or start jupyter differently, then you have to recreate it. File should have entry like `c.NotebookApp.extra_static_paths = ['/path/to/root/js/']`

**Comment by DraTeots** [comment] 2020-03-04 18:19
```
c.NotebookApp.extra_static_paths = ['/path/to/root/js/']
```
That is what I and probably everyone running standalone jupyter need. Checking...

**Comment by evan012345** [comment] 2020-06-24 13:29
@etejedor @DraTeots 

I am trying the new support for Jupyterlab in ROOT6.20 and I cannot get jsroot to work. It works in a Jupyter notebook, but not Jupyter lab. my Root build commands were:
cmake -Dminuit2=ON -Droofit=ON -Dclad=OFF -Dhttp=ON -Dpython=ON -DPYTHON_EXECUTABLE=/usr/local/anaconda3/install/bin/python -DPYTHON_INCLUDE_DIR=/usr/local/anaconda3/install/include/python3.6m/ ../root-6.20.04/ 

I'm running everything on a server, so I port forward then run my jupyter notebook or lab session. Running:
jupyter notebook --port=8890 --no-browser 
**WORKS** - jsroot works just fine (as is did in previous Root 6 releases). I had to first use @linev suggestion above to add c.NotebookApp.extra_static_paths = ['/path/to/root/js/'] to jupyter_notebook_config.py

Running:
jupyter lab --port=8890 --no-browser 
Does **NOT** work. Output from the server shown below. There doesn't seem to be any obvious errors, so I'm not sure what the issue is. Plots with jsroot on simply do not show up, if I turn off jsroot classic static Root plots are displayed.

[I 08:55:24.190 LabApp] JupyterLab beta preview extension loaded from /usr/local/anaconda3/install/lib/python3.6/site-packages/jupyterlab
[I 08:55:24.191 LabApp] JupyterLab application directory is /home/local/anaconda3/install/share/jupyter/lab
[W 08:55:24.194 LabApp] JupyterLab server extension not enabled, manually loading...
[I 08:55:24.194 LabApp] JupyterLab beta preview extension loaded from /usr/local/anaconda3/install/lib/python3.6/site-packages/jupyterlab
[I 08:55:24.194 LabApp] JupyterLab application directory is /home/local/anaconda3/install/share/jupyter/lab
[I 08:55:24.200 LabApp] Serving notebooks from local directory: /home/rande/Geant4/simulations/RPM/hpge
[I 08:55:24.200 LabApp] 0 active kernels
[I 08:55:24.200 LabApp] The Jupyter Notebook is running at:
[I 08:55:24.200 LabApp] http://localhost:8890/?token=3f7bcef39ac69a01e41d1dfe63f6a9cb5d8a362656cd6e54
[I 08:55:24.200 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:55:24.200 LabApp]
 
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=3f7bcef39ac69a01e41d1dfe63f6a9cb5d8a362656cd6e54&token=3f7bcef39ac69a01e41d1dfe63f6a9cb5d8a362656cd6e54
[I 08:55:30.694 LabApp] 302 GET /?token=3f7bcef39ac69a01e41d1dfe63f6a9cb5d8a362656cd6e54&token=3f7bcef39ac69a01e41d1dfe63f6a9cb5d8a362656cd6e54 (::1) 1.16ms
[I 08:55:32.168 LabApp] Build is up to date
[I 08:55:32.319 LabApp] Kernel started: 84bde92c-2464-470e-8430-91004193577d
[I 08:55:34.523 LabApp] Adapting to protocol v5.1 for kernel 84bde92c-2464-470e-8430-91004193577d
[I 08:55:34.524 LabApp] Adapting to protocol v5.1 for kernel 84bde92c-2464-470e-8430-91004193577d
[I 08:55:38.066 LabApp] Starting buffering for 84bde92c-2464-470e-8430-91004193577d:bfd88e319fa6da27b2fc027c804647e1
[I 08:55:43.135 LabApp] Kernel restarted: 84bde92c-2464-470e-8430-91004193577d
[I 08:55:45.512 LabApp] Adapting to protocol v5.1 for kernel 84bde92c-2464-470e-8430-91004193577d
[I 08:55:45.514 LabApp] Restoring connection for 84bde92c-2464-470e-8430-91004193577d:bfd88e319fa6da27b2fc027c804647e1
[I 08:55:45.514 LabApp] Replaying 8 buffered messages
[I 08:57:32.118 LabApp] Saving file at /PlotSimulationData-Copy1.ipynb

Thanks for any help,
Cheers,
Evan

**Comment by agoose77** [comment] 2020-07-07 07:55
@evan012345 JSRoot is working for me, though in the latest release (6.22.00) there is a bug in the JSRoot painter which stops it from drawing. You should check for JS errors in the developer console of your browser if you want to look for JSRoot issues, as it is a JS extension.

I use `ROOTSYS` to set my extra static paths:
`c.LabApp.extra_static_paths = [os.path.join(os.environ['ROOTSYS'], 'js')]`

**Comment by linev** [comment] 2020-07-10 12:56
@agoose77 
Your solution only working if `thisroot.sh` script was called before - which is 99% of use cases.
But there is also situations when ROOT installed in system directories and does not require `thisroot.sh`.
I have suspect, that notebook configuration may be wrong - we need some testing here.

**Comment by agoose77** [comment] 2020-07-10 16:17
> @agoose77
> Your solution only working if `thisroot.sh` script was called before - which is 99% of use cases.
> But there is also situations when ROOT installed in system directories and does not require `thisroot.sh`.
> I have suspect, that notebook configuration may be wrong in such situation - we need some testing here.

If this is a possibility, then it would probably be better to use `root-config --prefix` to obtain the prefix, e.g. 
```python
import os, subprocess
prefix_path = subprocess.run(["root-config", "--prefix"], capture_output=True).stdout.decode().strip()

c.LabApp.extra_static_paths = [os.path.join(prefix_path, 'js')]
```

**Comment by linev** [comment] 2020-08-13 14:50
Some news.

After https://github.com/root-project/root/pull/6155 and https://github.com/root-project/root/pull/6169 PRs (both are merged into the master) `jupyter notebook` and `jupyter lab` works properly, including JSROOT graphics. 

With small adjustment in https://github.com/root-project/root/pull/6180 `require.js` will be excluded from `jupyter lab` - JSROOT can be loaded directly.

**Comment by DraTeots** [comment] 2020-08-13 23:38
Nice! Especially require.js! In which ROOT version will it appear?

**Comment by linev** [comment] 2020-08-14 06:27
It will be in next 6.24 release, planned for end 2020

**Comment by DraTeots** [comment] 2021-02-01 01:32
Well, jupyter says
```
'extra_static_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
```

**Comment by linev** [comment] 2021-02-01 08:14
As I can see, `extra_static_paths` configured only for NotebookApp by ROOT.
Probably Jupyter itself now adds another configuration.
As long as NotebookApp configuration used - everything will be fine from ROOT point of view

**Comment by agoose77** [comment] 2021-02-01 08:45
JupyterLab 3.0 now depends upon Jupyter Server instead of Jupyter Notebook to provide the server implementation. There is a compatibility shim in place which copies over legacy Notebook configuration. However, where Jupyter Server shares the same trait names, it will not shim those across. It means that a new `jupyter_server_config` file will need to be created that sets these duplicated traits:
https://jupyter-server.readthedocs.io/en/stable/operators/migrate-from-nbserver.html

**Comment by linev** [comment] 2021-02-01 08:49
> https://jupyter-server.readthedocs.io/en/stable/operators/migrate-from-nbserver.html

I guess, it is important information for @etejedor, who is maintaining `Jupyter` implementation for ROOT.

**Comment by linev** [comment] 2021-06-25 10:33
Seems to be, last issues with `jupyter lab` will be solved by https://github.com/root-project/root/pull/8538
Also fixed problem with `nbviewer` - now created notebooks can be directly viewed with https://nbviewer.jupyter.org/github/linev/examples/blob/master/notebook/try.ipynb

I closing issue, feel free to reopen it or create new one

**Closed by linev** 2021-06-25 10:33 UTC
