### ISSUE TITLE
Unable to load ROOT file (suspect: https)

### ISSUE THREAD

**Issue by alexandertuna** [root-project/jsroot#189] opened 2019-09-04 13:33 UTC
Hi jsroot developers. I have a question about loading a ROOT file into the online display. For example, if I go here:

https://jsroot.gsi.de/latest/?file=https://atlas-bb5.cern.ch/bb5_web/files/run_1565946687003.hist.root

It fails, and I'm told "Read docu how to open files from other servers.", even though https://atlas-bb5.cern.ch/bb5_web/files/run_1565946687003.hist.root is a legitimate file which I can download and view by hand.

I was wondering if you had this experience before. I suspect it is related to our website (atlas-bb5.cern.ch) recently moving from http to https, but I don't understand how this affects the jsroot side.

Thanks for any help,

Alex

cc @sezata @grabanal

**Comment by linev** [comment] 2019-09-04 13:37
Hi Alex,

Problem is CORS - Cross Origin Requests. They are blocked by default in the browsers:

https://github.com/root-project/jsroot/blob/master/docs/JSROOT.md#reading-root-files-from-other-servers

Either you configure your server or you need to install JSROOT on your server and use it from there. Typically second solution is much easier.

Regards,
Sergey

**Comment by alexandertuna** [comment] 2019-09-04 14:48
Hi Sergey,

What if I have jsroot installed on this server:
https://atlas-bb5.cern.ch/jsroot/index.htm

And yet it still cannot open the file?
https://atlas-bb5.cern.ch/jsroot/index.htm?file=https://atlas-bb5.cern.ch/bb5_web/files/run_1565946687003.hist.root

**Comment by alexandertuna** [comment] 2019-09-04 15:31
Hi again Sergey,

I see that this link works correctly on Safari and Firefox, but not on Google Chrome. So I cannot blame you for me having Chrome as my default browser.

In case you have any further suggestions, please let me know. Otherwise we will simply use firefox and move on.

Alex

**Comment by linev** [comment] 2019-09-05 07:34
First of all, my browsers reporting problem with invalid SSL certificate.
Probably this has side effects.

But I can confirm that Chrome does not work when Firefox does.
Seems to be, there is tiny difference between HTTP requests issued by these browsers. 
As a result, server sends wrong response to Chrome - ignoring range supplied in HTTP request.

As a workaround you can use "+" sign after file name:

https://atlas-bb5.cern.ch/jsroot/index.htm?file=../bb5_web/files/run_1565946687003.hist.root+

But it means that complete file content will be loaded into the browser (for that particular case it is 55 MB).

And I will try to find better solution.

**Comment by linev** [comment] 2019-09-05 09:23
Hi Alex,

It is interplay between wrong SSL certificate, Chrome and your HTTP server.
As a result, at some situation HTTP server returns wrong "Content-Length" value in HTTP response header. And JSROOT uses such header to prevent loading of huge data into the browser - there are other error situations when server ignore ranges and try to send complete file content.

For your problem I provide a workaround, which can be activated with **wrong_http_response** URL parameter.

http://jsroot.gsi.de/dev/?wrong_http_response&file=https://atlas-bb5.cern.ch/bb5_web/files/run_1565946687003.hist.root

You can download it from: http://jsroot.gsi.de/dev/JsRootDev.tar.gz

You can just edit in code to enable workaround by default (line 105 in JSRootCore.js):

JSROOT.wrong_http_response_handling = true; 

Or add this code after loading of JSRootCore.js script.

Regards,
Sergey

**Comment by alexandertuna** [comment] 2019-09-05 16:30
Thanks very much Sergey.

**Comment by linev** [comment] 2019-09-05 16:37
I closing issue.

**Closed by linev** 2019-09-05 16:37 UTC

**Comment by linev** [comment] 2021-01-06 08:21
In JSROOT v 6.0.0 flag will be renamed to:
```
JSROOT.settings.HandleWrongHttpResponse = true;
```

**Comment by linev** [comment] 2024-11-05 12:42
In JSROOT v 7.x it is:
```
import { settings } from 'jsroot';
settings.HandleWrongHttpResponse = true;
```
