### ISSUE TITLE
How to set Axis titles for Tgraph?

### ISSUE THREAD

**Issue by piotrpolec** [root-project/jsroot#225] opened 2021-12-20 17:51 UTC
Hey,
Is there a way to name x and y axis? I've found [this closed issue](https://github.com/root-project/jsroot/issues/126) that was supposed to add the functionality in 5.2, but haven't found anything in the changelog. There's nothing about in the JSROOT documentation and `fXaxis` and `fYaxis` are both  undefined for `TGraph` objects.

**Comment by linev** [comment] 2021-12-20 20:52
Hi,

`fXaxis` and `fYaxis` objects are not existing in `TGraph` - they belong to histogram object, which stored in `fHistogram` data member. Like in [example](https://jsroot.gsi.de/dev/api.htm#custom_html_tlegend_src) from #126 you can create histogram object and assigned it to the TGraph:
```
         let h1 = JSROOT.createHistogram("TH1I", 20);
         h1.fName = "axis_draw";
         h1.fXaxis.fTitle = "xaxis";
         h1.fYaxis.fTitle = "yaxis";
         h1.fXaxis.fXmin = -60;
         h1.fXaxis.fXmax = +60;

         let gr = JSROOT.createTGraph(3, [1,2,3], [5,2,5]);
         gr.fHistogram = h1;
```
This functionality should be working since jsroot 5.2 - with some adjustments done for 6.0 release.

Regards,
Sergey

**Comment by grzanka** [comment] 2021-12-21 12:15
Thank you @linev for this answer. Seems tricky but useful.
Can you also advise us on how to centre the axis description?

BTW, what is the reason behind having `fHistogram` data member in TGraph ? The purpose of TGraphs seems very different from TH* classes, therefore I do not see any need for a histogram there.

**Comment by linev** [comment] 2021-12-21 12:42
> BTW, what is the reason behind having fHistogram data member in TGraph ? 

It is how ROOT graphics work. To draw axes for TGraph, TH1 object is created and drawn first.

> Can you also advise us on how to centre the axis description?

To center axis title, one do: `h1.fXaxis.InvertBit(JSROOT.BIT(12))` or `h1.fXaxis.InvertBit(JSROOT.EAxisBits.kCenterTitle)`.

like [TAxis::CenterTitle()](https://root.cern.ch/doc/v624/classTAxis.html#a7eeb578be928e04606ed5510d8472953) function does, see also [source code](https://root.cern.ch/doc/v624/TAxis_8h_source.html#l00184)

**Comment by Mexolius** [comment] 2021-12-28 17:44
I was trying to follow the setps but something is up with the `fHistogram`. Namely when you try to display the object of TMultiGraph (or TGraph) the `fHistogram` is present, but once you try to access it in any way it turns into `null`.

![image](https://user-images.githubusercontent.com/39342674/147592655-a1cc1683-34b8-4f77-82e4-5f2a1640c566.png)

The first output is simply `console.log(myTMultiGraph)`
The second is direct access with `console.log(myTMultiGraph.fHistogram)`
The third is `console.log(Object.entries(myTMultiGraph)`

Is there any better way to get the the fHistogram?

**Comment by linev** [comment] 2021-12-28 18:54
https://root.cern/js/latest/api.htm#custom_html_tlegend

Here is example of `TMultiGraph` with custom `fHistogram` to draw labels instead of numbers.
And this is source:

https://github.com/root-project/jsroot/blob/master/demo/multigraph_legend.htm

If you have problems, try to create reproducer using web site like https://jsfiddle.net/

**Comment by grzanka** [comment] 2022-01-02 17:12
@linev thank you for providing very good resources !

@piotrpolec am I right that the problem was fixed in https://github.com/APTG/dedx_web/pull/165/files#diff-9c81996045285b5c46a45a0b72b1c24a4d9c43df9ca6aadc841898e9a606d4f1R33
?

Our web app has now nice axis labels, as seen here https://aptg.github.io/web_dev/StoppingPower

I think we could close that issue now and start working on another problem, reported here: https://github.com/APTG/dedx_web/issues/174

**Closed** 2022-02-03 10:10 UTC
Labels: question
